version: '3.4'

services: 
  api:
    image: recipes-api
    build:
      context: Recipes.API
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    networks:
      - "recipes_api_net"

networks:
  recipes_api_net:
    driver: bridge